#! /usr/bin/env python

"""
A task generator that will copy a file from the source directory
to another file in the build directory

Try:
$ waf configure clean build
"""

top = '.'
out = 'build'

def configure(conf):
	pass

def build(bld):
	bld(
		rule   = 'cp ${SRC} ${TGT}',
		source = 'wscript',
		target = 'foobar.txt',
	)

