#! /usr/bin/env python

"""
$ waf configure ping
"""

top = '.'
out = 'build_directory'

def configure(ctx):
    print('→ configuring the project in ' + ctx.path.abspath())

def ping(ctx):
    print('→ ping from ' + ctx.path.abspath())
    ctx.recurse('src')
