#!/usr/bin/python 
import os
import subprocess
from optparse import OptionParser

if not os.path.exists ("build/configured"):
	print ("Project is not configured")
	exit (1)

parser = OptionParser()
parser.add_option("-p", "--prefix", dest="prefix", help="install prefix", metavar="PREFIX")
parser.add_option("-d", "--dest", dest="dest", help="install to this directory", metavar="DEST")

(options, args) = parser.parse_args()

if not options.prefix:
	options.prefix = "/usr/local"

if not options.dest:
	options.dest = ""

prefix = options.prefix
dest = options.dest

subprocess.check_output ('install -d ' + dest + prefix + '/share/birdfont/layout', shell=True)
for file in os.listdir('./layout'):
	subprocess.check_output ('install layout/' + file + ' ' + dest + prefix + '/share/birdfont/layout/', shell=True)

subprocess.check_output ('install -d ' + dest + prefix + '/share/birdfont/icons', shell=True)
for file in os.listdir('./icons'):
	subprocess.check_output ('install icons/' + file + ' ' + dest + prefix + '/share/birdfont/icons/', shell=True)

subprocess.check_output ('install -d ' + dest + prefix + '/share/applications/', shell=True)
subprocess.check_output ('install linux/birdfont.desktop ' + dest + prefix + '/share/applications/', shell=True)

subprocess.check_output ('install -d ' + dest + prefix + '/share/icons/hicolor/48x48/apps/', shell=True)
subprocess.check_output ('install linux/birdfont.png ' + dest + prefix + '/share/icons/hicolor/48x48/apps/', shell=True)

subprocess.check_output ('install -d ' + dest + prefix + '/bin/', shell=True)
subprocess.check_output ('install build/birdfont ' + dest + prefix + '/bin/', shell=True)

subprocess.check_output ('install -d ' + dest + prefix + '/bin/', shell=True)
subprocess.check_output ('install build/birdfont-export ' + dest + prefix + '/bin/', shell=True)

subprocess.check_output ('install -d ' + dest + prefix + '/lib/', shell=True)
subprocess.check_output ('install build/libbirdfont.so ' + dest + prefix + '/lib/', shell=True)

subprocess.check_output ('install -d ' + dest + prefix + '/share/man/man1/', shell=True)
subprocess.check_output ('install build/birdfont.1.gz ' + dest + prefix + '/share/man/man1/', shell=True)
subprocess.check_output ('install build/birdfont-export.1.gz ' + dest + prefix + '/share/man/man1/', shell=True)
