#!/usr/bin/python 
import os
import subprocess
from scripts.run import run

if not os.path.exists ("build/configured"):
	print ("Project is not configured")
	exit (1)

if not os.path.exists ("build/installed"):
	print ("Project is not installed")
	exit (1)

f = open('build/installed')
for file in iter(f):
	print ('Removing ' + file.replace ('\n', ''))
	run ('rm ' + file)

f.close()
