#! /usr/bin/env python

"""
The context methods may execute the same methods from waf tools

observe how the dang.py file is used and compare

$ waf configure build
$ waf configure build --dang=test
"""

top = '.'
out = 'build'

def options(ctx):
	ctx.load('dang', tooldir='.')

def configure(ctx):
	ctx.load('dang', tooldir='.')

def build(ctx):
	print(ctx.env.DANG)

