#! /usr/bin/env python

"""
To list the targets to build, use 'waf list'

Try the following
$ waf configure clean build
$ waf list
$ waf clean build --targets=bar
"""

top = '.'
out = 'build'

def configure(ctx):
    pass

def build(ctx):
    ctx(source='wscript', target='foo.txt', rule='cp ${SRC} ${TGT}')
    ctx(target='bar.txt', rule='touch ${TGT}', name='bar')
