#! /usr/bin/env python

"""
the command 'foo' uses a build context subclass internally
try calling 'waf configure foo'
"""

def configure(ctx):
	ctx.env.FOO = 'some data'

def build(ctx):
	print('build command')

def foo(ctx):
	print(ctx.env.FOO)

from waflib.Build import BuildContext
class one(BuildContext):
	cmd = 'foo'
	fun = 'foo'
