#! /usr/bin/env python

"""
The call 'add_group' is used to split the build:
all the tasks from one group will be executed before the
tasks from the next group are even considered

$ waf configure clean build
"""

top = '.'
out = 'build'

def configure(ctx):
	ctx.load('g++')
	ctx.load('src2cpp', tooldir='.')

def build(ctx):
	ctx.program(
		source = 'comp.cpp',
		target = 'comp')

	ctx.add_group()

	ctx.program(
		source = 'main.cpp a.src',
		target = 'foo')

