.TH BIRDFONT-IMPORT 1 LOCAL

.SH NAME
birdfont-import - Add several SVG files to a font file
.SH SYNOPSIS
.B birdfont-import birdfont-file svg-files ...
.SH DESCRIPTION
birdfont-import 
birdfont-import will generate a birdfont file from a set of SVG images. 
The command assumes that the file name denotes either a single character
or a Unicode value on the form U+XX where XX is the Unicode number in
hexadecimal format.

See also birdfont-export for creating SVG, EOT and TTF fonts from the
birdfont file.

See http://birdfont.org for use cases.
.SH AUTHOR
Johan Mattsson
