.TH BIRDFONT-EXPORT 1 LOCAL

.SH NAME
birdfont-export - generate TTF, EOT and SVG files from BIRDFONT files
.SH SYNOPSIS
.B birdfont-export [options] file
.SH DESCRIPTION
birdfont-export generates fonts that can be installed and on 
your computer or deployed on your website.

See https://birdfont.org for use cases.
.SH OPTIONS
.TP 5
\--filter [characters]
Include only these characters
.TP
\-h, \--help
Print command line options.
.TP
\-o, \--output [directory]
Write files to this directory
.TP
\-s, \--svg
Write SVG font
.TP 
\-t, \--ttf
Write TTF and EOT fonts
.SH AUTHOR
Johan Mattsson
