#! /usr/bin/env python

"""
A simple build - the file foo.txt is used both as target and as source
Note that the correct build order is computed automatically

$ waf configure clean build
"""

top = '.'
out = 'build_directory'

def configure(ctx):
	pass

def build(ctx):
	ctx(rule='touch ${TGT}', target='foo.txt')
	ctx(rule='cp ${SRC} ${TGT}', source='foo.txt', target='bar.txt')

