#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	bld.recurse('test0 test1')

	obj = bld(
			features = 'cxx cxxstlib',
			source   = 'main.cpp',
			use      = 'CPPUNIT',
			target   = 'unittestmain')

