#! /usr/bin/env python

"""
The node objects behave like singletons (one node <-> one path)

Try:
$ waf configure dosomething
"""

top = '.'
out = 'build'

def configure(ctx):
	pass

def dosomething(ctx):
	print(ctx.root.children)

