#! /usr/bin/env python
# encoding: utf-8
# Jaap Haitsma, 2008
# Thomas Nagy, 2010

bld.program(
	packages      = 'gtk+-2.0',
	target        = 'vala-gtk-example',
	uselib        = 'GTK GLIB',
	source        = 'vala-gtk-example.vala',
	vala_defines  = ['DEBUG']
	)

