#! /usr/bin/env python

"""
The 4 wrappers program, stlib, shlib and objects are aliases for bld(features='..', ..)
where the features can be
c, cshlib, cstlib, cprogram, cxx, cxxshlib, cxxstlib, cxxprogram, d, dshlib, ...
"""

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')

def build(bld):
	bld.program(source='main.c', target='app', use='myshlib mystlib')
	bld.stlib(source='a.c', target='mystlib')
	bld.shlib(source='b.c', target='myshlib', use='myobjects')
	bld.objects(source='c.c', target='myobjects')

