#! /usr/bin/env python

"""
This example illustrates how to navigate in the node tree

Try:
$ waf configure dosomething
"""

top = '.'
out = 'build'

def configure(ctx):
	pass

def dosomething(ctx):
	print(ctx.path.abspath())
	print(ctx.root.abspath())
	print("ctx.path contents %r" % (ctx.path.children))
	print("ctx.path parent   %r" % ctx.path.parent.abspath())
	print("ctx.root parent   %r" % ctx.root.parent)
