#! /usr/bin/env python

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('compiler_cxx protoc')

def build(bld):
	bld(
		features = 'cxx cxxshlib',
		source   = ['inc/message.proto'],
		target   = 'somelib',
		includes = ['.', 'inc'])

