#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008-2010 (ita)

VERSION='0.0.1'
APPNAME='cc_test'

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('compiler_cxx doxygen')

def build(bld):
	# Note: Doxgen parameters may be passed using pars attribute
	#       e.g. pars={'EXCLUDE_PATTERNS':'*.babu'}

	if bld.cmd == 'doxy':
		bld(
			features='doxygen',
			doxyfile='test.conf',
			doxy_tar='docs.tar.bz2')
	else:
		print('Call "waf doxy" for building the documentation')

from waflib import Build
class doxy(Build.BuildContext):
	fun = 'build'
	cmd = 'doxy'

