#! /usr/bin/env python

"""
special include flags
$ waf configure clean build
"""

top = '.'
out = 'build'

def configure(conf):
	conf.load('g++')

def build(bld):
	bld.program(features='cxx cxxprogram', source='main.cpp', target='test')

from waflib.TaskGen import after, feature

@feature('cxx')
@after('apply_incpaths')
def insert_blddir(self):
	self.env.prepend_value('INCPATHS', '.')

@feature('cxx')
@after('apply_incpaths', 'insert_blddir')
def insert_srcdir(self):
	path = self.bld.srcnode.abspath()
	self.env.prepend_value('INCPATHS', path)

