#! /usr/bin/env python

"""
Execute
$ 'waf cnt'
the cnt context is defined in 'some_tool.py'
"""

top = '.'
out = 'build'

def options(opt):
	opt.load('some_tool', tooldir='.')

def configure(conf):
	pass

