#! /usr/bin/env python

"""
Calling 'waf clean build' can be shortened to 'waf cleanbuild'
The cleanbuild command is defined below
"""

def configure(ctx):
	pass

def build(ctx):
	pass

def cleanbuild(ctx):
	from waflib import Options
	Options.commands = ['clean', 'build'] + Options.commands

