#! /usr/bin/env python

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')

	conf.check_cfg(atleast_pkgconfig_version='0.0.0')
	pango_version = conf.check_cfg(modversion='pango')

	conf.check_cfg(package='pango')
	conf.check_cfg(package='pango', uselib_store='MYPANGO',
		args=['--cflags', '--libs'])

	conf.check_cfg(package='pango',
		args=['pango >= 0.1.0', 'pango < 9.9.9', '--cflags', '--libs'],
		msg="Checking for 'pango 0.1.0'")

	conf.check_cfg(path='sdl-config', args='--cflags --libs',
		package='', uselib_store='SDL')
	conf.check_cfg(path='mpicc', args='--showme:compile --showme:link',
		package='', uselib_store='OPEN_MPI', mandatory=False)

