#! /usr/bin/env python

"""
The configuration tests such as conf.check* do not have to execute
c/c++ tests. By changing the features, it is possible to turn
almost any kind of build into a configuration test

Try 'waf configure' and look at the config.log file
"""

from waflib.TaskGen import feature, before_method

@feature('special_test')
@before_method('process_source')
def my_special_test(self):
	self.bld(rule='touch ${TGT}', target='foo')
	self.bld(rule='cp ${SRC} ${TGT}', source='foo', target='bar')
	self.source = []

def configure(conf):
	conf.check_cc(features='special_test', msg='my test!')

