#! /usr/bin/env python

"""
The conf.env object is an instance of waflib.ConfigSet.ConfigSet

It is used as a serializable dict to hold any kind of useful data
"""

top = '.'
out = 'build'

def configure(ctx):
	ctx.env.FOO = 'TEST'
	node = ctx.path.make_node('test.txt')

	env_copy = ctx.env.derive()
	env_copy.store(node.abspath())

	from waflib.ConfigSet import ConfigSet
	env2 = ConfigSet()
	env2.load(node.abspath())

	print(node.read())

