#! /usr/bin/env python

"""
This example demonstrates a few attributes that may be passed to
bld.program, bld.shlib and bld.stlib
"""

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')

def build(bld):
	bld.program(
		source       = 'main.c',
		target       = 'appname',
		features     = ['more', 'features', 'here'],

		includes     = ['.'],
		defines      = ['LINUX=1', 'BIDULE'],

		lib          = ['m'],
		libpath      = ['/usr/lib64'],
		stlib        = ['dl'],
		stlibpath    = ['/usr/local/lib'],
		linkflags    = ['-g'],

		install_path = '${SOME_PATH}/bin', # None to disable
		vnum         = '1.2.3',
		ccflags      = ['-O2', '-Wall'],
		cxxflags     = ['-O3'],
		rpath        = ['/opt/kde/lib']
	)

