#! /usr/bin/env python

bld.shlib(
	#packages = 'gtk+-2.0',
	features = 'c cshlib',
	target   = 'hello-world',
	#uselib   = 'GTK GLIB',
	source   = 'hello.vala',
	gir      = 'hello-1.0',
	#gir_path  = '/tmp',
	#vapi_path = '/tmp',
	pkg_name = 'hello'
	)

