#! /usr/bin/env python

"""
Create task generators to create tasks when necessary,
it is equivalent to the example 'build_manual_tasks'

$ waf configure clean build
"""

def configure(ctx):
	pass

def build(ctx):
	ctx(rule='cp ${SRC} ${TGT}', source='wscript', target='foo.txt')
	ctx(rule='cp ${SRC} ${TGT}', source='wscript', target='bar.txt')
	ctx(rule='cat ${SRC} > ${TGT}', source='foo.txt bar.txt', target='foobar.txt')

