top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_cxx boost')

def configure(conf):
    conf.load('compiler_cxx boost')
    conf.check_boost('system filesystem', mt=True)

def build(bld):
    bld.program(source='main.cpp', target='app', use='BOOST')
