#! /usr/bin/env python

"""
Tests should not rely on return codes and will return exceptions
in case of errors
"""

top = '.'
out = 'build'

def configure(ctx):
    try:
        ctx.find_program('some_app')
    except ctx.errors.ConfigurationError:
        ctx.to_log('some_app was not found (ignoring)')
