.TH BIRDFONT 1 LOCAL

.SH NAME
birdfont - font editor
.SH SYNOPSIS
.B birdfont [file] [options]
.SH DESCRIPTION
birdfont lets you edit and create font files.

See http://birdfont.org
.SH OPTIONS
.TP
-c, --show-coordinates
show coordinate in glyph view
.TP
-e, --exit
exit if a testcase failes
.TP
-f, --fatal-warning
treat warnings as fatal
.TP
-h, --help
show command line options
.TP
-s, --slow
sleep between each command in test suite
.TP
-t [testcase]
run tests
.SH AUTHOR
Johan Mattsson
