def build (bld):
	bld (
		rule = 'gzip -9 -c ../linux/birdfont.1  > ${TGT}',
		target = '../build/birdfont.1.gz'
	)
		
	bld (
		rule = 'gzip -9 -c ../linux/birdfont-export.1 > ${TGT}',
		target = '../build/birdfont-export.1.gz'
	)

	bld.install_files('${PREFIX}/share/man/man1/', ['../build/birdfont.1.gz', '../build/birdfont-export.1.gz'])
