#! /usr/bin/env python

"""
Context commands usually derive from different classe.
The command 'foo' uses a normal context, while bar uses
a different class. Try executing
$ waf configure foo bar tak
"""

def configure(ctx):
	print(type(ctx))

def foo(ctx):
	print(type(ctx))

def bar(ctx):
	print(type(ctx))

from waflib.Context import Context

class one(Context):
	cmd = 'foo'

class two(Context):
	cmd = 'tak'
	fun = 'bar'

