#! /usr/bin/env python

"""
Typical projects are build by using:
$ waf configure build
Other build commands may build the same project in a different output directory
$ waf configure debug
"""

def configure(ctx):
	pass

def build(ctx):
	ctx(rule='touch ${TGT}', target=ctx.cmd + '.txt')

from waflib.Build import BuildContext
class debug(BuildContext):
	cmd = 'debug'
	variant = 'debug'

